MQTT_BROKER_URL: broker.hivemq.com
MQTT_LOGGING: true
LOGGING_FILE: flask_mqtt.log
LOGGING_LEVEL: 10
LOGGING_FORMAT: "%(asctime)s--%(name)s--%(levelname)s--%(message)s"
WEBSERVER_LOGGING_LEVEL: 20
CONTACT_FILE: contact.csv
CONTACT_DEFAULT_NUMBER: "94960307"